version: "3.6"

services:
  backend:
    image: shiksha-lms-service
      build:
        context: .
        dockerfile: Dockerfile
    container_name: "shiksha-lms-service"
    restart: always
    ports:
      - 4000:4000
    env_file:
      - /.env