version: "3.6"

services:
  backend:
    image: shiksha-lms-service
    container_name: "shiksha-lms-service"
    restart: always
    ports:
      - 5000:5000
    env_file:
      - /home/ubuntu-shiksha-lms-service/.env