apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: shiksha-lms-service
  name: shiksha-lms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiksha-lms-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shiksha-lms-service
    spec:
      containers:
      - image: ${ECR_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: "Always"
        name: shiksha-lms-service
        ports:
        - name: http
          containerPort: 4000
        envFrom:
        - configMapRef:
            name: shiksha-lms-service-config
        # Liveness probe - checks if container is alive
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness probe - checks if service is ready (DB connected)
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        # Startup probe - gives more time for initial startup
        startupProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
        resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: shiksha-lms-service
spec:
  type: ClusterIP
  ports:
  - port: 4000
    protocol: TCP
  selector:
    app: shiksha-lms-service
