name: Aspire-Deploy to dev
on:
  push:
    branches:
      - release-1.0.0
jobs:
  deploy_to_server1:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy Stack 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_AL }}
          username: ${{ secrets.USERNAME_AL }}
          key: ${{ secrets.SSH_PRIVATE_KEY_AL }}
          port: ${{ secrets.PORT_AL }}
          script: |
            cd /home/ubuntu/Aspire-leader-dev/MICROSERVICES/SHIKSHA-LMS-SERVICE
            ./deploy.sh
